version: '3'

services:
  api-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_new_bot
    ports:
      - 3006:3006
    restart: always
    networks:
      - home
networks:
  home:
    driver: bridge
